[package]
name = "aeronum-transformer-demo"
version = "0.1.0"
authors = ["Robert Van Arsdale <robert.vanarsdale@gmail.com>"]
description = "Aero Ecosystem Flagship GPT-2 Transformer Demonstration"

[dependencies]
aeronum = "0.1.0"
aeronn = "0.1.0"
aeronum-gpu = "0.1.0"

[features]
cuda_backend = []
