[package]
name = "aeronum-gpu"
version = "0.1.0"
authors = ["Robert Van Arsdale <robert.vanarsdale@gmail.com>"]
description = "Aero GPU Acceleration Backend Architecture"

[dependencies]
aeronum = "0.1.0"

[features]
cuda_backend = []
opencl_backend = []
