[package]
name = "aeronum-docs"
version = "0.1.0"
authors = ["Robert Van Arsdale <robert.vanarsdale@gmail.com>"]
description = "Aero Official Documentation Static-Site Generator"

[dependencies]
aeronum = "0.1.0"
aeronn = "0.1.0"
aeronum-gpu = "0.1.0"
